---

- hosts: all
  gather_facts: no
  vars_prompt:
   - name: "user_name"
     prompt: "Enter the user name: "
     private: no
   - name: "sudo_user"
     prompt: "Sudo user is require or not (yes/no)? "
     private: no
  become: true
  roles:
    - user
